### ISSUE TITLE
Classless reverse subnet

### ISSUE THREAD

**Issue by wilix** [operasoftware/dns-ui#108]
We have multiple separated IPv4 /26 and  IPv4 /28 subnets.
How can I create an classless IPv4 subnet  as reverse IPv4 zone?

192.168.1.192/26 isn't recognized as prefix when create an IPv4 reverse zone for 192/26.1.168.192.in-addr.arpa

It isn't possible to order a single /24 because our ISP is out of IPv4 stock.

**Comment by thomas-pike** [comment]
I think this question is a bit out of scope for the DNS UI, but:

Managing your own reverse zone is normally only possible if the ISP delegates the appropriately named zone (of the form `d.c.b.a.in-addr.arpa`) to your DNS server. Since the `in-addr.arpa` lookup scheme only works in /24 /16 and /8 cases, your ISP cannot delegate the zone to you in this way.

There are 2 options to work around this:
1. Leave your ISP to manage the reverse zone and send them requests for changes when you need them.
2. Have your ISP use CNAME records within their `in-addr.arpa` zone to point the specific /26 and /28 subnets to records within zones that you manage. This mechanism is described in [RFC 2317](https://tools.ietf.org/html/rfc2317).
